In [8]:
#Create an array with the values from 0 .. 23. And Check its attributes.
import numpy as np
arr1 = np.arange(start=0, stop=24)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
24
4
int32


In [12]:
#Reshape it as 2*12
arr1=np.arange(24).reshape(2,12)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(2, 12)
24
4
int32


In [13]:
#Reshape it as 3*8
arr1=np.arange(24).reshape(3,8)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
(3, 8)
24
4
int32


In [14]:
#Reshape it as 4*6
arr1=np.arange(24).reshape(4,6)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
24
4
int32


In [17]:
#Reshape it as 2*2*6
arr1=np.arange(24).reshape(2,2,6)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
(2, 2, 6)
24
4
int32


In [18]:
#Reshape it as 2*4*3
arr1=np.arange(24).reshape(2,4,3)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)
24
4
int32


In [19]:
#Reshape it as 3*4*2
arr1=np.arange(24).reshape(2,4,3)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)
24
4
int32


In [25]:
Array1 =  [5,7,9,8,6,4,5]
Array2 = [6,3,4,8,9,7,1]

def calculate(x):
    return (x=np.maximum(Array1,Array2))
cal = np.vectorize(calculate)
cal([x])

SyntaxError: invalid syntax (<ipython-input-25-2ee8bb1b6784>, line 5)

In [35]:
#Write a Numpy program to generate six random integers between 10 and 30
from numpy import random
for x in range(6):
    print (random.randint(10,30))

27
16
19
21
23
19


In [38]:
#Get all the items between 5 and 10 from Array A.
def calculate(x):
    return 5>x<10
cal = np.vectorize(calculate)
cal([2,6,1,9,10,3,27])

array([ True, False,  True, False, False,  True, False])

In [44]:
#Extract all odd numbers from the array.
a = np.array([2,6,1,9,10,3,27])
only_odd = [num for num in a if num % 2 == 1] 
print(only_odd)

[1, 9, 3, 27]
